# Generated by Django 4.2.3 on 2023-08-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='сourse',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время обновления'),
        ),
    ]
