# Generated by Django 4.2.3 on 2023-07-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinsky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='описание')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
